/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MethodRouteImport } from './routes/method'
import { Route as WatchlistRouteImport } from './routes/watchlist'
import { Route as GemSymbolRouteImport } from './routes/gem.$symbol'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MethodRoute = MethodRouteImport.update({
  id: '/method',
  path: '/method',
  getParentRoute: () => rootRouteImport,
} as any)
const WatchlistRoute = WatchlistRouteImport.update({
  id: '/watchlist',
  path: '/watchlist',
  getParentRoute: () => rootRouteImport,
} as any)
const GemSymbolRoute = GemSymbolRouteImport.update({
  id: '/gem/$symbol',
  path: '/gem/$symbol',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/watchlist': typeof WatchlistRoute
  '/gem/$symbol': typeof GemSymbolRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/watchlist': typeof WatchlistRoute
  '/gem/$symbol': typeof GemSymbolRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/method': typeof MethodRoute
  '/watchlist': typeof WatchlistRoute
  '/gem/$symbol': typeof GemSymbolRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/method' | '/watchlist' | '/gem/$symbol'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/method' | '/watchlist' | '/gem/$symbol'
  id: '__root__' | '/' | '/method' | '/watchlist' | '/gem/$symbol'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MethodRoute: typeof MethodRoute
  WatchlistRoute: typeof WatchlistRoute
  GemSymbolRoute: typeof GemSymbolRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/method': {
      id: '/method'
      path: '/method'
      fullPath: '/method'
      preLoaderRoute: typeof MethodRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/watchlist': {
      id: '/watchlist'
      path: '/watchlist'
      fullPath: '/watchlist'
      preLoaderRoute: typeof WatchlistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gem/$symbol': {
      id: '/gem/$symbol'
      path: '/gem/$symbol'
      fullPath: '/gem/$symbol'
      preLoaderRoute: typeof GemSymbolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MethodRoute: MethodRoute,
  WatchlistRoute: WatchlistRoute,
  GemSymbolRoute: GemSymbolRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
